BROKER_URL = 'redis://redis:6379/10'
CELERY_BROKER_URL = BROKER_URL
CELERY_RESULT_BACKEND = BROKER_URL
CELERY_ENABLE_UTC = True
CELERY_TIMEZONE = 'UTC'

CELERY_ACKS_LATE = True
CELERYD_PREFETCH_MULTIPLIER = 1

CELERY_EMAIL_TASK_CONFIG = {'ignore_result': True}
CELERY_REDIS_MAX_CONNECTIONS = 300
CELERY_ACCEPT_CONTENT = ['pickle', 'json']
CELERYD_MAX_TASKS_PER_CHILD = 1

CELERYBEAT_MAX_LOOP_INTERVAL = 60

CELERYBEAT_SCHEDULE = {
}


