# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-01-17 13:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import djangocms_filer_video.fields.video


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('djangocms_filer_video', '0004_auto_20171123_1311'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_video', djangocms_filer_video.fields.video.FilerVideoFileField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='example_model_video', to='djangocms_filer_video.VideoFile', verbose_name='Main video')),
            ],
        ),
    ]
